import type { CommProfile } from './packetLoss'

const EXAMPLE_NOTE =
  'DropSim example profile. These numbers are user-defined assumptions for comparison, not a manufacturer rating and not a measured link.'

export const commProfiles: CommProfile[] = [
  {
    id: 'example-short-range',
    name: 'Example short-range link',
    carrierFrequencyHz: 2.4e9,
    dataRateBps: 250_000,
    packetBytes: 64,
    intervalS: 0.05,
    latencyS: 0.04,
    jitterS: 0.01,
    latencyPerMeter: 0,
    nominalRangeM: 800,
    retryCount: 1,
    retryGapS: 0.02,
    bandwidthHz: 1_000_000,
    loss: { kind: 'distance', baseLoss: 0.01, midpointM: 800, steepness: 0.01, maxLoss: 0.85 },
    rssiAtOneMeterDbm: -40,
    pathLossExponent: 2.2,
    source: 'DropSim built-in example',
    sourceDate: '2026-01-01',
    confidence: 'user-defined',
    notes: EXAMPLE_NOTE,
  },
  {
    id: 'example-poor',
    name: 'Example poor link',
    carrierFrequencyHz: 433e6,
    dataRateBps: 9_600,
    packetBytes: 48,
    intervalS: 0.2,
    latencyS: 0.12,
    jitterS: 0.04,
    latencyPerMeter: 0,
    nominalRangeM: 400,
    retryCount: 0,
    retryGapS: 0.05,
    bandwidthHz: 125_000,
    loss: { kind: 'distance', baseLoss: 0.05, midpointM: 350, steepness: 0.02, maxLoss: 0.95 },
    rssiAtOneMeterDbm: -45,
    pathLossExponent: 2.6,
    source: 'DropSim built-in example',
    sourceDate: '2026-01-01',
    confidence: 'user-defined',
    notes: EXAMPLE_NOTE,
  },
  {
    id: 'example-good',
    name: 'Example good link',
    carrierFrequencyHz: 900e6,
    dataRateBps: 1_000_000,
    packetBytes: 80,
    intervalS: 0.02,
    latencyS: 0.015,
    jitterS: 0.003,
    latencyPerMeter: 0,
    nominalRangeM: 2000,
    retryCount: 2,
    retryGapS: 0.01,
    bandwidthHz: 2_000_000,
    loss: { kind: 'distance', baseLoss: 0.002, midpointM: 2000, steepness: 0.006, maxLoss: 0.5 },
    rssiAtOneMeterDbm: -35,
    pathLossExponent: 2,
    source: 'DropSim built-in example',
    sourceDate: '2026-01-01',
    confidence: 'user-defined',
    notes: EXAMPLE_NOTE,
  },
  {
    id: 'ideal',
    name: 'Ideal link (perfect delivery)',
    carrierFrequencyHz: 0,
    dataRateBps: 10_000_000,
    packetBytes: 64,
    intervalS: 0.02,
    latencyS: 0,
    jitterS: 0,
    latencyPerMeter: 0,
    nominalRangeM: 100_000,
    retryCount: 0,
    retryGapS: 0.01,
    bandwidthHz: 10_000_000,
    loss: { kind: 'constant', baseLoss: 0, midpointM: 1, steepness: 0, maxLoss: 0 },
    rssiAtOneMeterDbm: 0,
    pathLossExponent: 0,
    source: 'DropSim idealization',
    sourceDate: '2026-01-01',
    confidence: 'user-defined',
    notes: 'Zero loss and zero latency. A comparison baseline, not a radio.',
  },
]

export function profileById(id: string): CommProfile {
  return commProfiles.find((profile) => profile.id === id) ?? commProfiles[0]
}
