import type { ComponentRecord } from './schema'

/**
 * Names below are examples of hardware a study might consider.
 * Numeric specifications are intentionally empty. Import a datasheet or type the values.
 * Empty fields are not applied to the physics model.
 */
export const starterCatalog: ComponentRecord[] = [
  {
    id: 'cuav-x7-plus',
    manufacturer: 'CUAV',
    model: 'X7+',
    category: 'flight-controller',
    price: null,
    currency: null,
    weightKg: null,
    dimensionsM: null,
    voltageV: null,
    currentA: null,
    interfaces: [],
    protocols: [],
    updateRateHz: null,
    accuracy: null,
    accuracyUnit: null,
    rangeM: null,
    sourceUrl: null,
    sourceDate: null,
    specificationSource: 'Not loaded. Enter or import a datasheet before using this as a preset.',
    confidence: 'unspecified',
    userNotes: 'Placeholder entry. No manufacturer numbers are shipped with DropSim.',
    rawSpecification: '',
  },
  {
    id: 'siderion-dp0601',
    manufacturer: 'Siderion',
    model: 'DP0601',
    category: 'gnss',
    price: null,
    currency: null,
    weightKg: null,
    dimensionsM: null,
    voltageV: null,
    currentA: null,
    interfaces: [],
    protocols: [],
    updateRateHz: null,
    accuracy: null,
    accuracyUnit: null,
    rangeM: null,
    sourceUrl: null,
    sourceDate: null,
    specificationSource: 'Not loaded. Enter or import a datasheet before using this as a preset.',
    confidence: 'unspecified',
    userNotes: 'Placeholder entry. Specifications are unknown to DropSim until imported.',
    rawSpecification: '',
  },
  {
    id: 'emax-eco-ii-2807',
    manufacturer: 'EMAX',
    model: 'ECO II 2807',
    category: 'motor',
    price: null,
    currency: null,
    weightKg: null,
    dimensionsM: null,
    voltageV: null,
    currentA: null,
    interfaces: [],
    protocols: [],
    updateRateHz: null,
    accuracy: null,
    accuracyUnit: null,
    rangeM: null,
    sourceUrl: null,
    sourceDate: null,
    specificationSource: 'Not loaded. Enter or import a datasheet before using this as a preset.',
    confidence: 'unspecified',
    userNotes: 'Placeholder entry. Motor specifications are not guessed.',
    rawSpecification: '',
  },
  {
    id: 'generic-4s-pack',
    manufacturer: 'Unspecified',
    model: '4S pack',
    category: 'battery',
    price: null,
    currency: null,
    weightKg: null,
    dimensionsM: null,
    voltageV: null,
    currentA: null,
    interfaces: [],
    protocols: [],
    updateRateHz: null,
    accuracy: null,
    accuracyUnit: null,
    rangeM: null,
    sourceUrl: null,
    sourceDate: null,
    specificationSource: 'Not loaded.',
    confidence: 'unspecified',
    userNotes: 'A 4S label is not a capacity, mass, or current rating. Import the pack you intend to buy.',
    rawSpecification: '',
  },
]
